version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: Postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: notes
    volumes:
      - .postgreSQL:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  notes:
    container_name: Notes
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 3003:3003
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-data:
